[workspace]
resolver = "2"
members = ["demos/*", "paekli-rs/impl/*"]
exclude = [
    "demos/day_4/serde",      # needs its own serde to learn about missing features
    "demos/day_4/cargo_deny", # don't check workspace licenses
]
