# default
import = [
    "~/.config/alacritty/themes/vscode.toml",
    "~/.config/alacritty/config.toml",
]

# overrides
[font]
size = 24

[window]
padding = { x = 96, y = 0 }

[colors.bright]
green = "#85d067"
red = "#ff724e"
