name: Deploy paekli-rs book
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@main
      - name: Deploy paekli-rs book to GitHub Pages
        run: ./dev/scripts/deploy_gh_pages.sh
